config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "messages#index"

  resources :messages do
    collection do
      get 'search'
    end

    resources :comments, only: :create

    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, name: "趣味"}, {id: 2, name: "暮らし"}, {id: 3, name: "スポーツ"},
    {id: 4, name: "学習"}, {id: 5, name: "ビジネス"}, {id: 6, name: "音楽"},
    {id: 7, name: "社会"}, {id: 8, name: "芸術"}, {id: 9, name: "文化"}
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes
    has_many :comments 
    mount_uploader :image, ImageUploader
    with_options presence: true do
      validates :title
      validates :content
      validates :category_id
      validates :image
    end

    def liked_by?(user)
      likes.where(user_id: user.id).exists?
    end

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :category

  def self.search(search)
    if search != ""
      Message.where('title LIKE(?)', "%#{search}%")
    else
      Message.all
    end
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :comments 
  has_many :likes, dependent: :destroy
  has_many :like_messages, through: :likes, source: :message
  
  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to message_path(params[:message_id])  }
        format.json
      end
    else
      @messages = messages.includes(:user)
      render :index
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_like

  def create
      user = current_user
      message = Message.find(params[:message_id])
      like = Like.create(user_id: user.id, message_id: message.id)
      @count=message.likes.length
  end
  def destroy
      user = current_user
      message = Message.find(params[:message_id])
      like = Like.find_by(user_id: user.id, message_id: message.id)
      like.delete
      @count=message.likes.length
  end

  private
  def set_like
    @message =Message.find(params[:message_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :find_message, only: [:show, :edit, :update, :check_user]
  before_action :check_user, only: [:edit, :update]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def show
    @count=@message.likes.length
    @comment = Comment.new
    @comments = @message.comments.includes(:user)
  end

  def edit 
  end

  def update
    if @message.update(message_params)
      redirect_to message_path(@message), notice: '投稿内容が編集されました'
    else
      flash.now[:alert] = '必要項目を入力してください'
      render :edit
    end
  end

  def destroy
    message = Message.find(params[:id]) 
    if current_user.id == message.user.id
      message.destroy
      redirect_to root_path
    else 
      redirect_to message_path(message.id)
    end
  end

  def search
    @messages = Message.search(params[:keyword])
  end
  

  def create
    @message = Message.new(message_params)
    if @message.valid?
      @message.save
      redirect_to root_path, notice: 'メッセージが送信されました'
    else
      flash.now[:alert] = '必要項目を入力してください'
      render "new"
    end
  end


  private
  def message_params
    params.require(:message).permit(:title, :content, :image,:category_id).merge(user_id: current_user.id)
  end

  def find_message
    @message = Message.find(params[:id])  
  end

  def check_user
    if @message.user_id != current_user.id
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hataage
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/likes/_like.html.haml
- if current_user == nil
  = link_to message_add_path(message), method: :post, remote: true, class: "like", id: "like-button-#{message.id}" do
    = icon('fas', 'fa-lg fas fa-star icon-btn not-like')
    %span.not-like-number
      =count
- elsif message.liked_by?(current_user)
  = link_to message_add_path(message), method: :delete, remote: true, class: "like",id: "like-button-#{message.id}" do
    = icon('fas', 'fa-lg fa-heart icon-btn liked')
    %span.liked-number
      =count
- else 
  = link_to message_add_path(message), method: :post, remote: true, class: "like", id: "like-button-#{message.id}" do
    = icon('fas', 'fa-lg fas fa-star icon-btn not-like')
    %span.not-like-number
      =count

app/views/likes/create.js.erb
$("#like-button-<%= @message.id %>").html("<%= escape_javascript(render partial: "likes/like", locals: { message: @message ,count:@count}) %>");

app/views/likes/destroy.js.erb
$('#like-button-<%= @message.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { message: @message,count:@count }) %>");

app/views/messages/_button.html.haml
= link_to new_message_path, class: 'link-button' do
  .link-button__icon
    %span.link-button__icon__letter
      POST
    %span
    = image_tag "pen-icon.png", size: "54x54", class: 'link-button__icon__image'

app/views/messages/_header.html.haml
.top-header
  .header-box
    = link_to 'hataage', root_path, class: 'header-title'

.three-box
  .left
    .left__box 
      .left__box__search
        =form_with url: search_messages_path, method: :get, class: 'left__box__search__form' ,local: true do |f|
          = f.text_field :keyword,class: 'left__box__search__form__word',placeholder: 'キーワードから探す'
          .left__box__search__form__send
            %button{type: "submit", class:'left__box__search__form__send__btn'}  
              %i.fas.fa-search


  %ul.right-bottom
    - if user_signed_in?
      %li.right-bottom__button
        = link_to 'マイページ', edit_user_path(current_user), class: 'right-bottom__button__registration'
      %li.right-bottom__button
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'right-bottom__button__login'

    - else
      %li.right-bottom__button
        = link_to 'ログイン', new_user_session_path, class: 'right-bottom__button__login'
      %li.right-bottom__button
        = link_to '新規会員登録', new_user_registration_path, class: 'right-bottom__button__registration'

app/views/messages/_main.html.haml
.message
  - @messages.each do |message|
    = link_to message_path(message), class: 'message__box' do
      .message__box__title 
        =message.title
        %p.message__box__icon
          = message.user.name

app/views/messages/edit.html.haml
.new-page
  =form_with model: @message, html: {class: "new-box"}, local: true do |f|
    .new-box__title
      %label タイトル
      =f.text_field :title, class: "new-box__title__form", placeholder:"４０文字まで"

    .new-box__category
      %label カテゴリー
      = f.collection_select :category_id, Category.all, :id, :name,{include_blank:"選択してください"},{class: "new-box__category__form"}

    .new-box__image
      %label 投稿画像
      .new-box__image__file
        = f.label :image, class: 'new-box__image__file__upload' do
          = icon('fas', 'camera', class: 'new-box__image__file__upload__icon')
          = f.file_field :image, class: 'new-box__image__file__upload__file'

    .new-box__content
      %label 記事の本文
      =f.text_area :content, class: "new-box__content__text", rows:'15', maxlength: '1000'

    .new-box__submit
      = f.submit "編集完了",class:"new-box__submit__btn"
      
    .new-box__return
      = link_to 'もどる', root_path, class: "new-box__return__btn"

app/views/messages/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "button"  

app/views/messages/new.html.haml
= render "header" 
.new-page
  =form_with model: @message, html: {class: "new-box"}, local: true do |f|
    .new-box__title
      %label タイトル
      =f.text_field :title, class: "new-box__title__form", placeholder:"2０文字まで"
    .new-box__category
      %label カテゴリー
      = f.collection_select :category_id, Category.all, :id, :name,{include_blank:"選択してください"},{class: "new-box__category__form"}

    .new-box__image
      %label 投稿画像
      .new-box__image__file
        = f.label :image, class: 'new-box__image__file__upload' do
          = icon('fas', 'camera', class: 'new-box__image__file__upload__icon')
          = f.file_field :image, class: 'new-box__image__file__upload__file'

    .new-box__content
      %label 記事の本文
      =f.text_area :content, class: "new-box__content__text", rows:'14', maxlength: '1000'

    .new-box__submit
      = f.submit "投稿する",class:"new-box__submit__btn"

app/views/messages/search.html.haml
= render "header" 
= render "button" 

%h2.result-title 
  【検索結果】

.result
  - @messages.each do |message|
    .result-box
      = link_to message_path(message), class: 'link-box' do
        .result-box__image
          %label 【投稿画像】
          .result-box__image__file
          = image_tag message.image.url, class: 'result-box__image__picture'

        .result-box__title
          %label 【タイトル】
          .result-box__title__data
            =message.title

        .result-box__category
          %label 【カテゴリー】
          .result-box__category__data
            =message.category.name

app/views/messages/show.html.haml
.show
  .show-box
    .show-box__image
      =image_tag @message.image.url, class: 'show-box__image__picture'

    .show-box__title
      %label タイトル
      .show-box__title__data
        = @message.title

    .show-box__category
      %label カテゴリー
      .show-box__category__data
        = @message.category.name

    .show-box__memo
      .show-box__memo__data
        = safe_join(@message.content.split("\n"),tag(:br))

    .show__good
      .show__good__box
        %p いいね！
        = render partial: 'likes/like', locals: { message: @message,count: @count}

    .container
      = form_with(model: [@message, @comment], html: {class: "Form"}, local: true, id: "new_comment") do |f|
        = f.text_field :text, placeholder: "コメントする", rows: "2", class:'text-box'
        %button{type: "submit", class:'send-box'}  
          %i.fas.fa-paper-plane

    .comment
      - @comments.each do |comment|
        .comment-box
          .comment-name
            = comment.user.name
          .comment-text
            = comment.text
             
    - if user_signed_in? && current_user.id == @message.user.id
      .show-box__content
        = link_to '投稿を編集する', edit_message_path(@message.id), class:"show-box__content__edit"
        = link_to '投稿を削除する', message_path(@message), method: :delete, class:"show-box__content__delete"


    = link_to 'トップページに戻る', root_path, class: 'return__button'

= render "button"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 登録情報
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "更新", class: 'Button UserButton'